export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_CONTINUE_URL = 'AUTH_SET_CONTINUE_URL';
export const AUTH_UPD_USERMETA = 'AUTH_UPD_USERMETA';
export const AUTH_LOADED = 'AUTH_LOADED';

export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_CHANGE_START = 'PROFILE_CHANGE_START';
export const PROFILE_CHANGE_SUCCESS = 'PROFILE_CHANGE_SUCCESS';
export const PROFILE_CHANGE_ERROR = 'PROFILE_CHANGE_ERROR';
